### ISSUE TITLE
Doesn't build with rust 1.0.0-beta

### ISSUE THREAD

**Issue by he-sk** [frankmcsherry/COST#3]
Hi,

apparently `std::os::MemoryMap` and `std::os::MapOption` got removed from the beta release. According to the rust IRC channel, there are bindings to mmap in https://github.com/carllerche/nix-rust/ but it's not a drop-in replacement.

The error message is:

```
Compiling COST v0.0.1 (file:///Users/hesk/unix/src/COST)
src/typedrw.rs:6:26: 6:37 error: unresolved import `std::os::MapOption::MapReadable`. Could not find `MapOption` in `std::os`
src/typedrw.rs:6 use std::os::MapOption::{MapReadable, MapFd};
                                          ^~~~~~~~~~~
src/typedrw.rs:6:39: 6:44 error: unresolved import `std::os::MapOption::MapFd`. Could not find `MapOption` in `std::os`
src/typedrw.rs:6 use std::os::MapOption::{MapReadable, MapFd};
                                                       ^~~~~
src/typedrw.rs:7:5: 7:23 error: unresolved import `std::os::MemoryMap`. There is no `MemoryMap` in `std::os`
src/typedrw.rs:7 use std::os::MemoryMap;
                     ^~~~~~~~~~~~~~~~~~
error: aborting due to 3 previous errors
Could not compile `COST`.
```

**Comment by frankmcsherry** [comment]
I'll take a peek! I'm currently running nightly rather than beta (for similar, but other reasons) but if I can get COST running on straight beta that would obviously be nice.

**Comment by he-sk** [comment]
They seem to be removed from the latest nightly as well, are they not?

**Comment by frankmcsherry** [comment]
You are correct, sir! Why would they do that to me... 

So, the only iffy thing I can think of wrt the nix-rust stuff is that the previous solution worked on Windows (I understand it is currently a non-solution). The other option is just deprecating the mmap based edge mapper for now and re-instating the two different versions (an in-memory mapper, and a from-storage mapper). Perhaps I could unify them by making them generic wrt a R: Read and either hand a file in or a &[u8].

Ok, ok. I'll get back to work. :)

**Comment by frankmcsherry** [comment]
Okies, I've got a version building against nightly. No clue how it performs or even if it is correct, but I'll try and look in to that tomorrow before pushing anything.

**Comment by frankmcsherry** [comment]
It seems like there is a drop-in replacement. The `mmap` crate on crates.io seems to be the code they ripped out of core Rust. So, I'll slot that in and ship a cleaned up version (there were many other issues). Currently waiting on a broken crate. :)

**Comment by frankmcsherry** [comment]
Ok, update pushed, but I forgot to close this as part of it. I haven't tested the new code yet, so except for the fact that it is very similar code to what was there before, not obvious that it should work / caveat emptor / testing stuff that runs on enormous amounts of data is hard. >.<
